name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: Swatinem/rust-cache@v2
        - name: Build
          run: sudo apt-get install -y protobuf-compiler && cargo build --release
        - name: Install nightly rustfmt
          run: rustup toolchain install nightly --component rustfmt
        - name: Check format
          run: cargo +nightly fmt --all --check